# Generated by Django 4.0.2 on 2022-12-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='birth_day',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='birth_month',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='birth_year',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='country',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='first_name',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='gender',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='home_address',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='last_name',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='middle_name',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='occupation',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='occupation_reason',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='phone_number',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='ssn_driver_back',
            field=models.FileField(default=True, upload_to='all_ssn_driver_back'),
        ),
        migrations.AddField(
            model_name='employees',
            name='ssn_driver_front',
            field=models.FileField(default=True, upload_to='all_snn_driver_front'),
        ),
        migrations.AddField(
            model_name='employees',
            name='state',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='employees',
            name='zip_code',
            field=models.CharField(default=True, max_length=1000),
        ),
    ]
